swagger: '2.0'
info:
  description: >-
    This document describes the pre-release API or interacting with
    [MyGet](https://www.myget.org). It is subject to change.
  version: 1.0.0-preview.1
  title: MyGet
  termsOfService: 'https://www.myget.org/policies/terms'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: sist-ucsb.myget.org
basePath: /
tags:
  - name: Users
    description: Resources related to users.
  - name: Feeds
    description: Resources related to feeds.
  - name: Feed privileges
    description: Resources related to feed privileges.
schemes:
  - https
paths:
  '/_api/v1/user/{username}':
    get:
      tags:
        - Users
      summary: Retrieve user details
      description: >-
        Retrieves user details for a given {username}. When the username `me` is
        passed in, will get details for the authenticated user instead.
      operationId: getUser
      security:
        - oauth2:
            - 'user:read'
        - bearerApiKey: []
    delete:
      tags:
        - Users
      summary: Delete a user
      description: >-
        Deletes a user. **Note that this operation must be enabled specifically
        for your user account by MyGet.**
      operationId: deleteUser
      security:
        - oauth2:
            - 'user:write'
        - bearerApiKey: []
  '/_api/v1/user/{username}/feeds':
    get:
      tags:
        - Users
        - Feeds
      summary: Retrieve feeds for a given user
      description: >-
        Retrieves feeds for a given {username}. When the username `me` is passed
        in, will get details for the authenticated user instead.
      operationId: getUserFeeds
      security:
        - oauth2:
            - 'user:read'
        - bearerApiKey: []
  /_api/v1/user:
    post:
      tags:
        - Users
      summary: Create a user
      description: >-
        Creates a user. **Note that this operation must be enabled specifically
        for your user account by MyGet.**
      operationId: postUser
      security:
        - oauth2:
            - 'user:write'
        - bearerApiKey: []
  '/_api/v1/feed/{feedname}':
    get:
      tags:
        - Feeds
      summary: Retrieve feed details
      description: 'Retrieves feed details for a given `{feedname}`.'
      operationId: getFeed
      security:
        - oauth2:
            - 'feed:read'
        - bearerApiKey: []
    put:
      tags:
        - Feeds
      summary: Updates a feed
      description: Updates a feed.
      operationId: updateFeed
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
    delete:
      tags:
        - Feeds
      summary: Deletes a feed
      description: Deletes a feed.
      operationId: deleteFeed
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
  /_api/v1/feed:
    post:
      tags:
        - Feeds
      summary: Create a feed
      description: Creates a feed.
      operationId: postFeed
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
  '/_api/v1/feed/{feedname}/privileges':
    get:
      tags:
        - Feed privileges
      summary: Retrieve feed privileges
      description: 'Retrieves feed privileges for a given `{feedname}`.'
      operationId: getFeedPrivileges
      security:
        - oauth2:
            - 'feed:read'
        - bearerApiKey: []
    post:
      tags:
        - Feed privileges
      summary: Assign privileges to user on feed
      description: >-
        Assign privileges to user on feed. The authenticated user must be owner
        or co-owner of the feed.
      operationId: postFeedPrivileges
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
  '/_api/v1/feed/{feedname}/privileges/{username}':
    put:
      tags:
        - Feed privileges
      summary: Update privileges for user on feed
      description: >-
        Update privileges for user on feed. The authenticated user must be owner
        or co-owner of the feed.
      operationId: updateFeedPrivilegesUser
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
    delete:
      tags:
        - Feed privileges
      summary: Delete privileges for user on feed
      description: >-
        Delete privileges for user on feed. The authenticated user must be owner
        or co-owner of the feed.
      operationId: deleteFeedPrivilegesUser
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
  '/_api/v1/feed/{feedname}/privileges/invitation/{invitation}':
    put:
      tags:
        - Feed privileges
      summary: Update privileges for invitation on feed
      description: >-
        Update privileges for invitation on feed. The authenticated user must be
        owner or co-owner of the feed.
      operationId: updateFeedPrivilegesInvitation
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
    delete:
      tags:
        - Feed privileges
      summary: Delete privileges for invitation on feed
      description: >-
        Delete privileges for invitation on feed. The authenticated user must be
        owner or co-owner of the feed.
      operationId: deleteFeedPrivilegesInvitation
      security:
        - oauth2:
            - 'feed:write'
        - bearerApiKey: []
securityDefinitions:
  oauth2:
    type: oauth2
    authorizationUrl: 'https://www.myget.org/notimplementedyet'
    flow: implicit
    scopes:
      'user:read': Read user-related data
      'user:write': Write user-related data
      'feed:read': Read feed-related data
      'feed:write': Write feed-related data
  bearerApiKey:
    type: apiKey
    name: Authorization
    in: header